### ISSUE TITLE
Fix: Add to cart

### ISSUE THREAD

**Issue by vanvuongngo** [gioboa/qwik-microfrontends#1]
Hi @gioboa,

your project is looking quite promising but I can not use the "Add to cart" button.
The communication feature between the mfe and the host is needed to clarify that the main pain point is solved with your solution.

This is shown when I click on a "Add to cart" button:
`Error: Internal assert, this is likely caused by a bug in Qwik: out of bounds inflate access`

<img width="866" alt="Bildschirmfoto 2024-09-18 um 22 25 22" src="https://github.com/user-attachments/assets/ba328d93-16c3-47c7-a556-efa3009c0a0a">

<img width="135" alt="Bildschirmfoto 2024-09-18 um 22 25 33" src="https://github.com/user-attachments/assets/fa189a05-eb2f-48d4-9193-249deff2feba">

Do you have a clue how to fix?
Dispatch events is working in your other project: https://github.com/gioboa/qwik-microfrontend-starter

Also the package versions are very old.

environment:
- Chrome Browser, Firefox

**Comment by gioboa** [comment]
Hi, thanks for your feedback.
I refactored the project with this commit 4cbd64895d40b3ced62ab76462487ce5907273ee
It's working now. Enjoy :)

**Comment by vanvuongngo** [comment]
Many thanks @gioboa and a completely innovative project :)
I like pnpm and its good enough to me.
Is there any change to get `nx` working?

**Comment by gioboa** [comment]
The latest version of Nx doesn't work in my local env with the latest version of Qwik. I spent 30min to figure out the problem and then I decided to refactor the project to make it tool agnostic.

**Comment by vanvuongngo** [comment]
Yeah, works great. `nx` is in use by bigger projects thats why I asked. May this is a hint why Qwik does not work with NX monorepo: https://github.com/QwikDev/qwik/issues/6785
